FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package.json ./
RUN yarn install --registry https://registry.npmmirror.com
COPY frontend/ .
ENV REACT_APP_BACKEND_URL=""
ENV NODE_OPTIONS="--max-old-space-size=1536"
RUN yarn build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
